version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-frontend-app:latest
    container_name: react-frontend-container
    command: sh -c "/app/build.sh"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: python-backend-flask-app:latest
    container_name: python-backend-flask-container
    ports:
      - "5000:8000"
    depends_on:
      - frontend