name: SonarQube Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.1.0
      with:
        projectBaseDir: ./backend
        args: >
          -Dsonar.organization=${{ secrets.MY_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.MY_PROJECT_KEY }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.verbose=true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}